# This file executes @push-based/user-flow against the served SSR version of the current PR
name: user-flow-ci
on:
  pull_request:
jobs:
  user-flow-integrated-in-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm ci
      - name: Executing user-flow CLI
        uses: push-based/user-flow-gh-action@v0.2.0
        with:
          verbose: 'on'
          rcPath: ./projects/movies-user-flows/.user-flowrc.ci-csr.json
      - name: Commit measures
        uses: EndBug/add-and-commit@v7
        with:
          author_name: push-based.io
          author_email: opensource@push-based.io
          message: 'Persist user-flow results'
          add: '*'
